name: school_admin
description: A school administrative desktop application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.65.0
  animate_do: ^3.1.2
  provider: ^6.1.1
  supabase_flutter: ^2.3.4
  file_picker: ^8.0.0
  shared_preferences: ^2.5.4
  csv: ^6.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
